### ISSUE TITLE
Some broken links in the `Channels` section

### ISSUE THREAD

**Issue by fukusuket** [flaviut/nim-by-example#105]
Hello, Thank you so much for great document :)

I found following  broken links in the [Channels section](https://nim-by-example.github.io/channels/). So I repoted.

- https://nim-lang.org/docs/channels_builtin.html
- https://nim-lang.org/docs/channels_builtin.html#example-passing-channels-safely

As far as I've researched, the information equivalent to the above is available in version `1.6.14` at the following link:
- https://nim-lang.org/1.6.14/channels_builtin.html
- https://nim-lang.org/1.6.14/channels_builtin.html#example-passing-channels-safely

The document equivalent to the above appears to be the following in version `2.0.0` released last month.
- https://nim-lang.org/2.0.0/system.html#system-module-misc
- https://nim-lang.org/2.0.0/system.html#example-passing-channels-safely

Is it a issue that should be fixed in the documentation on the [Nim side](https://github.com/nim-lang/Nim)?

Regards,

**Comment by flaviut** [comment]
Thanks for the heads up!

I would suggest that the Nim documentation change https://nim-lang.org/docs/channels_builtin.html to redirect to https://nim-lang.org/docs/system.html#example automatically, to avoid breaking the link.

I would also suggest that the nim documentation change the section header at https://nim-lang.org/docs/system.html#example to be "Channels example" in order to make it possible to more stably link to this section if a different example is also added to this page.

**Comment by fukusuket** [comment]
Thank you so much!
