### ISSUE TITLE
Please improve the OOP example code.

### ISSUE THREAD

**Issue by vinodvinu** [flaviut/nim-by-example#68]
Hi,
Please include these in a nim class
1. construtor  - (Overlaoding constructor)
2. desturctor
3. private & public functions in a class. 
4. static function in a class.
5. Please write code about famous Person class or Car class. 
6.  Using keyword "class" is still an enigma for me. Please clarify how to do this.

**Comment by vinodvinu** [comment]
If that is your intention, then please add these info to that page:
1. Where to add that maro ? (In a separate file or inside our file)

**Comment by flaviut** [comment]
> In a separate file or inside our file

Either would work fine. Macros can be imported/exported just like anything else in Nim.

I've clarified that the page is focused on teaching macros rather than teaching OOP in 042ffa0b2b62682afcacf301972278a6b371916f, so I'm going to close this issue. Please let me know if there's anything else that's unclear!
